-- MySQL Script generated by MySQL Workbench
-- 01/24/15 14:23:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HighSchool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HighSchool` ;

-- -----------------------------------------------------
-- Schema HighSchool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HighSchool` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `HighSchool` ;

-- -----------------------------------------------------
-- Table `HighSchool`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HighSchool`.`Student` (
  `Registration_number` INT NOT NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Date_of_birth` DATE NULL,
  PRIMARY KEY (`Registration_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HighSchool`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HighSchool`.`Teacher` (
  `idTeacher` INT NOT NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Date_of_birth` DATE NULL,
  PRIMARY KEY (`idTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HighSchool`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HighSchool`.`Course` (
  `idCourse` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Hours_by_week` INT NULL,
  `Teacher` INT NOT NULL,
  PRIMARY KEY (`idCourse`),
  CONSTRAINT `fk_Course_Teacher`
    FOREIGN KEY (`Teacher`)
    REFERENCES `HighSchool`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Course_Teacher_idx` ON `HighSchool`.`Course` (`Teacher` ASC);


-- -----------------------------------------------------
-- Table `HighSchool`.`Student_takes_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HighSchool`.`Student_takes_Course` (
  `Student_Registration_number` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  `First_partial_note` INT NULL,
  `Second_partial_note` INT NULL,
  `Third_partial_note` INT NULL,
  `Final_note` INT NULL,
  PRIMARY KEY (`Student_Registration_number`, `Course_idCourse`),
  CONSTRAINT `fk_Student_has_Course_Student1`
    FOREIGN KEY (`Student_Registration_number`)
    REFERENCES `HighSchool`.`Student` (`Registration_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `HighSchool`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Student_has_Course_Course1_idx` ON `HighSchool`.`Student_takes_Course` (`Course_idCourse` ASC);

CREATE INDEX `fk_Student_has_Course_Student1_idx` ON `HighSchool`.`Student_takes_Course` (`Student_Registration_number` ASC);


-- -----------------------------------------------------
-- Table `HighSchool`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HighSchool`.`Schedule` (
  `idSchedule` INT NOT NULL,
  `Since` TIME(6) NULL,
  `To` TIME(6) NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`idSchedule`),
  CONSTRAINT `fk_Schedule_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `HighSchool`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Schedule_Course1_idx` ON `HighSchool`.`Schedule` (`Course_idCourse` ASC);


-- -----------------------------------------------------
-- Table `HighSchool`.`Students_below`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HighSchool`.`Students_below` (
  `Student_Registration_number` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  `Average_note` INT NULL,
  `Asigned_Teacher` INT NOT NULL,
  PRIMARY KEY (`Student_Registration_number`),
  CONSTRAINT `fk_Students_below_Student1`
    FOREIGN KEY (`Student_Registration_number`)
    REFERENCES `HighSchool`.`Student` (`Registration_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_below_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `HighSchool`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_below_Teacher1`
    FOREIGN KEY (`Asigned_Teacher`)
    REFERENCES `HighSchool`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Students_below_Student1_idx` ON `HighSchool`.`Students_below` (`Student_Registration_number` ASC);

CREATE INDEX `fk_Students_below_Course1_idx` ON `HighSchool`.`Students_below` (`Course_idCourse` ASC);

CREATE INDEX `fk_Students_below_Teacher1_idx` ON `HighSchool`.`Students_below` (`Asigned_Teacher` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
